language: cpp

dist: trusty
sudo: required

# compilers to add to build matrix
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install liblua5.3-dev libSDL2-dev libSDL2_image-dev libSDL2_mixer-dev libSDL2_ttf-dev libglew-dev
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

# scripts to run before build
before_script:
  - cmake CMakeLists.txt

# build app, and run tests (ie make & make test)
script:
  - make all
  - ./ST_engine/src/test/assets_manager/asset_manager_test
  - ./ST_engine/src/test/audio_manager/audio_manager_test
