version: '1.0.{build}'

image: Visual Studio 2017

environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  CMAKE_INSTALL_PREFIX: $(APPVEYOR_BUILD_FOLDER)

platform:
  - x64
 
configuration:
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - set SDL_VIDEODRIVER dummy
  - set SDL_AUDIODRIVER dummy  

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake -G "NMake Makefiles" .
  - nmake all

test_script:
  - ctest -VV
 