version: '1.0.{build}'

image: Visual Studio 2017

environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  CMAKE_INSTALL_PREFIX: $(APPVEYOR_BUILD_FOLDER)

platform:
  - x64
 
configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - set SDL_VIDEODRIVER dummy
  - set SDL_AUDIODRIVER dummy
  - set CMAKE_INSTALL_PREFIX "$(APPVEYOR_BUILD_FOLDER)"
  - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - ctest