version: '1.0.{build}'

environment:
  NINJA_URL: "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"

init:
  # Get Ninja
  - cd ..
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\ninja > nul
  - set PATH=C:\ninja;%PATH%
  - ninja --version
  - cd slavictales

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - cmake -G "Ninja" . && cmake --build . --target ALL_BUILD

