version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

build_script:
  - cmake --build $(APPVEYOR_BUILD_FOLDER) --target all

