version: '1.0.{build}'

image: Visual Studio 2017

environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  CMAKE_INSTALL_PREFIX: $(APPVEYOR_BUILD_FOLDER)

platform:
  - x64
 
configuration:
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - set SDL_VIDEODRIVER dummy
  - set SDL_AUDIODRIVER dummy
  - set CMAKE_INSTALL_PREFIX "$(APPVEYOR_BUILD_FOLDER)"
  

build_script:
  - cmake -G "NMake Makefiles" .

test_script:
  - ctest -VV
 